### PR TITLE
Added Swifttube

### PR DESCRIPTION
**Pull request by gsoykan**
- **Project Name**: Swifttube
- **Project URL**: http://www.swifttube.co
- **Project Description**: curates iOS conference videos in one place.
- **Why it should be added to `awesome-vapor`**: Built with Server Side Swift Vapor Framework
- [x] Project has at least 15 stars (if it's a GitHub project)
- [x] Project supports Swift 4
- [x] Project supports at least Vapor 2
- [x] I used correctly sized dash and ended the entry with a full stop 🤓

### CODE REVIEW

**Comment by Voilane** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
74 | [301](https://httpstatuses.com/301) | https://github.com/twof/VaporMailgunService redirects to<br>https://github.com/vapor-community/VaporMailgunService


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by gsoykan** [comment]
> 1 Error
> 🚫	Found 1 link issue
> #### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)
> Line	Status	Link
> 74	[301](https://httpstatuses.com/301)	https://github.com/twof/VaporMailgunService redirects to
> https://github.com/vapor-community/VaporMailgunService
> Generated by 🚫 [Danger](http://danger.systems/)

Dear Voilane,
I forked the project from master branch just now.
So I do not understand how I could create this problem by only adding one line which is not relevant to the "VaporMailgunService"

**Comment by gsoykan** [comment]
Dear @Voilane,
What would be your suggestion for me? Because apart from "swifttube" the other project, in this case it is "VaporMailgunService", does not have any relation with us. I had only changed the link because that part raised an error. Hence I am not sure what I should I do? 
Best.

**Comment by Cellane** [comment]
Hello @gsoykan,

@Voilane is my bot, and a quite dumb one at times, sorry about that! 🤣 

It wants to make sure that all links are pointing to correct destinations (and contain no redirects), but at the same time emits a warning when more than one line of code is changed. I’m personally happy that you fixed the URL so that I don’t have to open another PR/adjust this PR just to fix the URL. Sometimes, it’s definitely fine to alter more than one line at a time in this repository – it depends on the situation.

Thank you for your contribution! I’ll merge the PR now. And thanks for using Vapor!

**Pull request merged**
